version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/Jackals Setup/mkdocs.yml

mkdocs:
  configuration: docs/Jackals Setup/mkdocs.yml

python:
  install:
    - requirements: docs/Jackals Setup/requirements.txt